run:
  timeout: 3m
linters:
  enable:
    - gci
    - gofmt
    - gosec
    - nilerr
    - unconvert
    - unparam
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
