version: "2"
run:
  timeout: 3m
linters:
  enable:
    - gosec
    - nilerr
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
formatters:
  enable:
    - gci
    - gofmt
